import { Outfit } from 'next/font/google'
import './globals.css'

const inter = Outfit({ subsets: ['latin'], weight: ['500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-white">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
